language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
  fast_finish: true
  allow_failures:
    - php: 7.4
    - php: 8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

cache:
  directories:
    - $HOME/.composer/cache

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs src tests --extensions=php --ignore=bootstrap --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml -v
  - vendor/bin/phpmd src,tests xml build/config/phpmd.xml
  - vendor/bin/phpunit -c phpunit.xml --verbose

after_script:
  - php vendor/bin/php-coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
